//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.Bidding.EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExtensionType
    {
        public ExtensionType()
        {
            this.Media = new HashSet<Media>();
        }
    
        public long ExtensionTypeId { get; set; }
        public string Ext { get; set; }
        public Nullable<long> MediaTypeId { get; set; }
    
        public virtual MediaType MediaType { get; set; }
        public virtual ICollection<Media> Media { get; set; }
    }
}
